### ISSUE TITLE
update code

### ISSUE THREAD

**Issue by 943fansi** [albertszg/Coreloss#1]
A great work. I read your paper and come here. Would you please update the code as soon as possible?

cheers!

**Comment by albertszg** [comment]
Thank you for reading and supporting us, we are starting another study based on this article and therefore may release the code later. We will compile and update the code as soon as we finish the follow-up work.

**Comment by 943fansi** [comment]
@albertszg Could you give an example about how to use?

**Comment by albertszg** [comment]
of course, I will give a simple example later.
